# Generated by Django 5.2.3 on 2025-07-21 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cover',
            field=models.ImageField(blank=True, default='', null=True, upload_to='recipes/covers/%Y/%m/%d/'),
        ),
    ]
